language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

before_install:
  - "perl5.18.1 cpanm -q Dist::Zilla"
  - "perl 5.18.1 dzil authordeps | perl5.18.1 cpanm -q"
  - "perl 5.18.1 dzil listdeps | perl5.18.1 cpanm -q"

install:
  - "perl5.18.1 dzil build"

script: "make test"

notifications:
  recipients:
    - mjdominus@gmail.com
  email:
    on_success: always
    on_failure: always
